# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Tue Dec 29 10:48:45 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(400, 300)
        self.verticalLayout_2 = QtGui.QVBoxLayout(settingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(settingsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.customWordlistTab = QtGui.QWidget()
        self.customWordlistTab.setObjectName("customWordlistTab")
        self.gridLayout = QtGui.QGridLayout(self.customWordlistTab)
        self.gridLayout.setObjectName("gridLayout")
        self.customWordsTextEdit = QtGui.QTextEdit(self.customWordlistTab)
        self.customWordsTextEdit.setUndoRedoEnabled(False)
        self.customWordsTextEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.customWordsTextEdit.setAcceptRichText(False)
        self.customWordsTextEdit.setObjectName("customWordsTextEdit")
        self.gridLayout.addWidget(self.customWordsTextEdit, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.customWordlistTab)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.customWordlistTab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.wordListSize1 = QtGui.QRadioButton(self.tab)
        self.wordListSize1.setObjectName("wordListSize1")
        self.verticalLayout_7.addWidget(self.wordListSize1)
        self.wordListSize2 = QtGui.QRadioButton(self.tab)
        self.wordListSize2.setObjectName("wordListSize2")
        self.verticalLayout_7.addWidget(self.wordListSize2)
        self.wordListSize3 = QtGui.QRadioButton(self.tab)
        self.wordListSize3.setChecked(True)
        self.wordListSize3.setObjectName("wordListSize3")
        self.verticalLayout_7.addWidget(self.wordListSize3)
        self.wordListSize4 = QtGui.QRadioButton(self.tab)
        self.wordListSize4.setObjectName("wordListSize4")
        self.verticalLayout_7.addWidget(self.wordListSize4)
        self.wordListSize5 = QtGui.QRadioButton(self.tab)
        self.wordListSize5.setChecked(False)
        self.wordListSize5.setObjectName("wordListSize5")
        self.verticalLayout_7.addWidget(self.wordListSize5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.settingsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.settingsTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.settingsTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.okayButton = QtGui.QPushButton(settingsDialog)
        self.okayButton.setObjectName("okayButton")
        self.horizontalLayout_3.addWidget(self.okayButton)
        self.applyButton = QtGui.QPushButton(settingsDialog)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout_3.addWidget(self.applyButton)
        self.cancelButton = QtGui.QPushButton(settingsDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label.setBuddy(self.customWordsTextEdit)

        self.retranslateUi(settingsDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), settingsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        settingsDialog.setWindowTitle(QtGui.QApplication.translate("settingsDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settingsDialog", "Please enter any custom words you would like to appear in the spell check, one per line.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customWordlistTab), QtGui.QApplication.translate("settingsDialog", "Custom Words", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settingsDialog", "Please select the size of the word completion database:", None, QtGui.QApplication.UnicodeUTF8))
        self.wordListSize1.setText(QtGui.QApplication.translate("settingsDialog", "Big", None, QtGui.QApplication.UnicodeUTF8))
        self.wordListSize2.setText(QtGui.QApplication.translate("settingsDialog", "Really Big", None, QtGui.QApplication.UnicodeUTF8))
        self.wordListSize3.setText(QtGui.QApplication.translate("settingsDialog", "Huge", None, QtGui.QApplication.UnicodeUTF8))
        self.wordListSize4.setText(QtGui.QApplication.translate("settingsDialog", "Super Huge", None, QtGui.QApplication.UnicodeUTF8))
        self.wordListSize5.setText(QtGui.QApplication.translate("settingsDialog", "Ginormous", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("settingsDialog", "Word lists", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settingsDialog", "No more settings for now...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), QtGui.QApplication.translate("settingsDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.okayButton.setText(QtGui.QApplication.translate("settingsDialog", "Okay", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("settingsDialog", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("settingsDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

